hr_leave_grant_app/urls.py
from django.urls import path
from hr_leave_grant_app.views import (  BeneficiaryListCreateAPIView,
                                        BeneficiaryDetailAPiView,
                                        DependentCreateAPIView,
                                        DependentDetailAPIView,

                                        BeneficiaryListView,
                                        BeneficiaryDetailView,
                                        BeneficiaryPaymentsDetailView,
                                        ConfirmPaymentView,
                                        CreateBeneficiaryView,
                                        CreateDependentView,
                                        PendingPaymentView,
                                        UpdateBeneficiaryView,
                                        UpdateDependentView,
                                        DependentListView,
                                        DependentOver18ListView,
                                        TransactionHistoryView)

urlpatterns = [
    path('api/beneficiaries/', 
        BeneficiaryListCreateAPIView.as_view(),
        name='beneficiary-list'),

    path('api/beneficiary/<int:pk>/',
        BeneficiaryDetailAPiView.as_view(),
        name='benficiary-detail'),    
    

    path('api/beneficiary/<int:beneficiary_pk>/dependent/',
        DependentCreateAPIView.as_view(),
        name='dependent-create'),

    
    path('api/dependent/<int:pk>/',
        DependentDetailAPIView.as_view(),
        name='dependent-detail'),

    path('',
        BeneficiaryListView.as_view(), 
        name='beneficiary'),

    path('hr/leave-grant/beneficiary/new/',
        CreateBeneficiaryView.as_view(), 
        name='beneficiary-new'),

    path('hr/leave-grant/beneficiary/update/<int:pk>',
        UpdateBeneficiaryView.as_view(), 
        name='beneficiary-update'),   

    path('hr/leave-grant/beneficiary/<int:pk>/',
        BeneficiaryDetailView.as_view(), 
        name='beneficiary-detail'),

     path('hr/leave-grant/beneficiary/<int:pk>/payment/',
        BeneficiaryPaymentsDetailView.as_view(), 
        name='beneficiary-payment'),

    path('hr/leave-grant/beneficiary/<int:pk>/payment/confirm/',
        ConfirmPaymentView.as_view(), 
        name='confirm-payment'),

    # path('hr/leave-grant/dependent/new/',
    #     CreateDependentView.as_view(), 
    #     name='dependent-new'),

    path('hr/leave-grant/beneficiary/<int:pk>/dependent/new/',
        CreateDependentView.as_view(), 
        name='dependent-new'),

    path('hr/leave-grant/dependent/<int:pk>/',
        UpdateDependentView.as_view(), 
        name='dependent-detail'),

    path('hr/leave-grant/dependent/all/',
        DependentListView.as_view(), 
        name='dependent-all'),

    path('hr/leave-grant/dependent/over18/',
        DependentOver18ListView.as_view(), 
        name='dependent-over18'),

    path('hr/leave-grant/payment/pending/',
        PendingPaymentView.as_view(), 
        name='pending-payment'),

    path('hr/leave-grant/payment/transaction-history/',
        TransactionHistoryView.as_view(), 
        name='transaction-history'),

]

hr_leave_grant_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hr_leave_grant_app.urls'))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr_leave_grant_app/models.py
from django.db import models
from django.urls import reverse
import datetime

class Leave_Grant_Level(models.Model):
    'The leave grant amount for each year and level'    
    level = models.CharField(max_length=20)
    leave_grant_percentage = models.PositiveIntegerField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['leave_grant_percentage', ]
        verbose_name_plural = 'Leave Grant Levels'
    
    def __str__(self):
        return f'{self.level}'


class Leave_Grant_Year_Value(models.Model):
    'Stores the value of the leave grant for each year'
    year = models.DateField(auto_now_add=False)
    value = models.DecimalField(max_digits=6,decimal_places=2)

    class Meta:
        ordering = ['-year']
        verbose_name_plural = 'Leave Grant Year Values'

    def __str__(self):
        return f'{self.year} - ${self.value}'
    


class Beneficiary(models.Model):
    'Beneficiary Bio Data'

    employee_id = models.CharField(max_length=5, unique=True, verbose_name="Employee ID")
    first_name = models.CharField(max_length=30, verbose_name="First Name")
    last_name = models.CharField(max_length=30, verbose_name="last Name")
    eligibility_date = models.DateField(auto_now_add=False, verbose_name="Eligibility Date")
    active = models.BooleanField(default=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    leave_grant_level = models.ForeignKey(Leave_Grant_Level, on_delete=models.PROTECT, related_name='leave_grant_levels', verbose_name="Leave Grant Level")
    job_title = models.CharField(max_length=100, verbose_name="Job Title")
    card = models.FileField(upload_to='leave_grant_cards/', blank=True, null=True, default=None)
    
    class Meta:
            verbose_name_plural = 'Beneficiaries'
            ordering = ['first_name', 'last_name']
   
    
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    
    def get_absolute_url(self):
        return reverse('beneficiary-detail', args=[str(self.id)])

   


class Dependent(models.Model):
    'Dependents Bio Data'
    DEPENDENT_TYPE_CHOICES = (
                    ('Daughter', 'Daughter'),
                    ('Father', 'Father'),
                    ('Husband', 'Husband'),
                    ('Mother', 'Mother'),
                    ('Son', 'Son'),
                    ('Wife', 'Wife'),
    )

    beneficiary = models.ForeignKey(Beneficiary, on_delete=models.CASCADE, related_name='dependent')    
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    dependent_type = models.CharField(max_length=20, choices=DEPENDENT_TYPE_CHOICES)
    date_of_birth = models.DateField(auto_now_add=False)
    active = models.BooleanField()
    further_education = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:        
        ordering = ['first_name', 'last_name']


    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def over_18(self):
        'Returns True if the dependents age > 18'
        return  int(((datetime.date.today() - self.date_of_birth).days) / 365.25) >= 18 


    # def get_absolute_url(self):
    #     return reverse('beneficiary-detail', args=[str(self.id)])


    


class Leave_Grant_Detail(models.Model):
    'Keeps track of leave grant payments for beneficiaries and dependents'
    beneficiary = models.ForeignKey(Beneficiary, on_delete=models.CASCADE, related_name='leave_grant_details')       
    payment_date = models.DateField(auto_now_add=False,blank=True, null=True)
    amount = models.DecimalField(max_digits=7,decimal_places=2)
    remarks = models.TextField(null=True,blank=True)
    transaction_year = models.DateField(blank=True, null=True) #Payment for specific year
    recorded_by = models.CharField(max_length=50, verbose_name="Recorded By", blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    class Meta:
        ordering = ['beneficiary', '-payment_date', ]
        verbose_name_plural = 'Leave Grant Details'

    def __str__(self):
        return f'{self.payment_date} - {self.amount} - {self.remarks}'

hr_leave_grant_app/forms.py
from hr_leave_grant_app.models import Beneficiary

class BeneficiaryForm(forms.ModelForm):
    class Meta:
        model = Beneficiary
        fields = '__all__'

hr_leave_grant_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.db.models import Sum

from django.views import View
from django.views.generic import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse,reverse_lazy
from rest_framework import generics
from rest_framework.filters import SearchFilter

from hr_leave_grant_app.pagination import SmallSetPagination

from hr_leave_grant_app.serializers import (BeneficiarySerializer,
                                            BeneficiaryDetailSerializer,
                                            DependentSerializer,
                                            LeaveGrantDetailSerializer,
                                            LeaveGrantLevelSerializer
                                            )
from hr_leave_grant_app.models import   (Beneficiary,
                                        Dependent,
                                        Leave_Grant_Detail,
                                        Leave_Grant_Level
                                        )
import datetime

                                        
class BeneficiaryListCreateAPIView(generics.ListCreateAPIView):
    queryset = Beneficiary.objects.all()
    serializer_class = BeneficiarySerializer
    filter_backends = [SearchFilter]
    search_fields = ["first_name", "last_name", "employee_id"]
    pagination_class = SmallSetPagination


class BeneficiaryDetailAPiView(generics.RetrieveUpdateDestroyAPIView): #might need to change this to listAPI
    queryset = Beneficiary.objects.all()
    serializer_class = BeneficiaryDetailSerializer
    search_fields = ["id"]

class DependentCreateAPIView(generics.CreateAPIView):
    'View to create dependents'
    queryset = Dependent.objects.all()
    serializer_class = DependentSerializer

    def perform_create(self, serializer):
        beneficiary_pk = self.kwargs.get('beneficiary_pk')
        beneficiary = get_object_or_404(Beneficiary, pk=beneficiary_pk)
        serializer.save(beneficiary=beneficiary)

class DependentDetailAPIView(LoginRequiredMixin,generics.RetrieveUpdateDestroyAPIView):
    'View to list individual dependent details'
    queryset = Dependent.objects.all()
    serializer_class = DependentSerializer


class BeneficiaryListView(LoginRequiredMixin,ListView):
    'Generic View to list Beneficiaries'
    model = Beneficiary
    paginate_by = 10

    def get_queryset(self):
        'Search for the name in the search form'
        queryset = super().get_queryset()
        search = self.request.GET.get('search')        
        if search:
            results = self.model.objects.filter(Q(first_name__icontains = search) | Q(last_name__icontains = search))
        else:
            results = self.model.objects.all()
        return results


class BeneficiaryPaymentsDetailView(LoginRequiredMixin,DetailView):
    'View to return all payments for the Beneficiary'
    model = Beneficiary
    template_name = 'hr_leave_grant_app/beneficiary_payment.html'

    def get_context_data(self, **kwargs):
        context = super(BeneficiaryPaymentsDetailView, self).get_context_data(**kwargs)
        outstanding = Leave_Grant_Detail.objects.filter(beneficiary=self.kwargs['pk']).exclude(payment_date__isnull=False)
        context['outstanding_payments'] = outstanding
        total = outstanding.aggregate(outstanding_total=Sum('amount'))
        context['outstanding_total'] = total
        # context['outstanding_total'] = outstanding.aggregate(outstanding_total=Sum('amount'))
        context['payments'] = Leave_Grant_Detail.objects.filter(beneficiary=self.kwargs['pk']).exclude(payment_date__isnull=True).order_by('-payment_date')        
        self.request.session['outstanding_total'] = str(total)        
        return context
        

class CreateBeneficiaryView(LoginRequiredMixin,CreateView):
    'View to create beneficiaries'
    model = Beneficiary
    template_name = 'hr_leave_grant_app/beneficiary_form.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse('beneficiary-detail', kwargs={'pk': self.object.id})

class UpdateBeneficiaryView(LoginRequiredMixin,UpdateView):
    model = Beneficiary    
    template_name = 'hr_leave_grant_app/beneficiary_form.html'
    fields = '__all__'
    
    def get_context_data(self, **kwargs):
        'Send the Update text to the form'
        context = super(UpdateBeneficiaryView, self).get_context_data(**kwargs)
        context['form_type'] = 'update'
        return context


class CreateDependentView(LoginRequiredMixin,CreateView):
    'View to create dependents'
    model = Dependent
    template_name = 'hr_leave_grant_app/dependent_form.html'
    fields = ['first_name', 'last_name', 'dependent_type', 'date_of_birth', 'active', 'further_education']
    

    def form_valid(self, form):
        try:
            beneficiary = get_object_or_404(Beneficiary,pk=self.kwargs['pk'])
            
        except Exception as e:
            return e
        form.instance.beneficiary = beneficiary
        return super(CreateDependentView, self).form_valid(form)

    def get_success_url(self):
        return reverse('beneficiary-detail', kwargs={'pk': self.kwargs['pk']})


class UpdateDependentView(LoginRequiredMixin,UpdateView):
    'View to update dependents'
    model = Dependent
    template_name = 'hr_leave_grant_app/dependent_form.html'
    fields = ['first_name', 'last_name', 'dependent_type', 'date_of_birth', 'active','further_education']
    
    def get_context_data(self, **kwargs):
        context = super(UpdateDependentView,self).get_context_data(**kwargs)
        context["form_type"] = 'update' 
        return context   
    

    def get_success_url(self):
        return reverse('beneficiary-detail', kwargs={'pk': self.request.session['beneficiary_id']})




class ConfirmPaymentView(LoginRequiredMixin,View):
    'Confirms and processes the payment authorisation request'
    template_name = 'hr_leave_grant_app/confirm_payment.html'

    def get(self, request,pk):
        'Display payment authorisation confirmation page'
        beneficiary_id = self.kwargs['pk'] #self.request.session['beneficiary_id']    
        outstanding_total = self.request.session['outstanding_total']

        try: 
            bene = Beneficiary.objects.get(id=self.kwargs['pk'])
        except Exception as e:
            print(e)
            
        return render(request, self.template_name, {'outstanding_total': outstanding_total,
                                                    'beneficiary_id': beneficiary_id,  
                                                    'bene': bene ,                                                 
                                                    })

    def post(self, request,pk):
        'Update the leave grant details table and redirect to payment details page'
        
        user = f'{request.user.first_name} {request.user.last_name}'
        try:
            updated_records = Leave_Grant_Detail.objects.filter(beneficiary=self.kwargs['pk'])\
                                                        .exclude(payment_date__isnull=False)\
                                                        .update(payment_date=datetime.date.today(),recorded_by=user)
                                                        
        except Exception as e:
            print(e)

        return redirect('beneficiary-payment',self.kwargs['pk'])
        

class PendingPaymentView(LoginRequiredMixin,ListView):
    'Return a list of Employees with pending payments'
    context_object = 'beneficiary'  
    paginate_by = 10  
    template_name = 'hr_leave_grant_app/pending_payment.html'
    queryset = Beneficiary.objects.filter(leave_grant_details__payment_date__isnull=True, leave_grant_details__amount__isnull=False).distinct()

    
class BeneficiaryDetailView(LoginRequiredMixin,DetailView):
    'View to return all details for the Beneficiary including dependents'
    model = Beneficiary
    template_name = 'hr_leave_grant_app/beneficiary_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BeneficiaryDetailView, self).get_context_data(**kwargs)       
        self.request.session['beneficiary_id'] = self.kwargs['pk']        
        return context

    
class DependentListView(LoginRequiredMixin,ListView):
    'Generic View to list All Dependents'
    model = Dependent
    paginate_by = 10
    template_name = 'hr_leave_grant_app/dependent_all.html'


class DependentOver18ListView(LoginRequiredMixin,ListView):
    'Generic View to list All child Dependents over 18 years old'
    model = Dependent
    paginate_by = 10
    template_name = 'hr_leave_grant_app/dependent_over18.html'    
    
    def get_queryset(self):
        'Search for dependents > 18'
        dependents = ['Son', 'Daughter']
        queryset = super().get_queryset()
        
        queryset = Dependent.objects.filter(dependent_type__in=dependents,active=True)
        return queryset


class TransactionHistoryView(LoginRequiredMixin,ListView):
    'View to list all records in the leave grant detail table'
    model = Leave_Grant_Detail
    paginate_by = 15
    template_name = 'hr_leave_grant_app/transaction_history.html'
    ordering = ['-transaction_year']

hr_leave_grant_app/templates/hr_leave_grant_app/beneficiary_create_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mt-4 justify-content-around">
    <div class="col-sm-5">
        
        <div class="card">
            <div class="card-title bg-primary text-white h3 text-center pt-2 pb-2">Beneficiary Details</div>
                <div class="card-body">
                    <form method="post" novalidate="novalidate">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <p class="text-center">
                            <input class="btn btn-outline-primary " type="submit" value="Add Beneficiary">
                        </p>                   

                    </form>
                </div>
            </div>
        </div>
                 
    </div>

    
   
</div>

  
{% endblock %}

{% block navbar %}
    {% include "hr_leave_grant_app/navbar-links.html" %}
{% endblock %}

hr_leave_grant_app/templates/hr_leave_grant_app/beneficiary_detail.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<div class="row justify-content-center">
<div class="col-sm-12">
   
<div class="card mt-5 card-border">
    <div class="card-body">
        <div >
            <h4 class="">Leave Grant</h4>
            <h2 class="">Beneficiary Details</h2>        
            <a href="{% url 'beneficiary-payment' beneficiary.pk %}" class="mt-3 btn btn-outline-primary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Payment Details">{{beneficiary.first_name}} {{beneficiary.last_name}}</a>
        </div>
       
        
        <div class="mt-5 pt-2">
            {% if beneficiary.card %}
            <h4 class="">Beneficiary <a href="{{beneficiary.card.url}}" target="_blank" ><i class="text-warning far fa-file-alt" data-bs-toggle="tooltip" data-bs-placement="right" title="View Leave Card"></i></a></h4>
            {% endif %}
        </div>
        

        <div class="mt-2">
            <table class="table table-hover table-top">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Eligibility Date</th>
                        <th>Leave Grant Level</th>
                        <th class="text-center">Active</th>                   
                    </tr>
                </thead>
                <tr class="row-hover" data-href="{% url 'beneficiary-update' beneficiary.pk %}">                    
                    <td><a class="" >{{beneficiary.first_name}}</a></td>
                    <td>{{beneficiary.last_name}}</td>
                    <td>{{beneficiary.eligibility_date}}</td>
                    <td>{{beneficiary.leave_grant_level}}</td>
                    <td class="text-center">
                        {% if beneficiary.active %}
                            <i class="far fa-check-circle active-check "></i>
                        {% else %}
                            <i class="far fa-times-circle active-x "></i>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
       
        
        <div class="mt-5 pt-2">
            <h4>Dependents <a href="{% url 'dependent-new' beneficiary.pk %}" class="pl-1"><i class=" text-warning fas fa-user-plus fa-xs" data-bs-toggle="tooltip" data-bs-placement="right" title="Add Dependent"></i></a></h4>
        </div>

        <div class="pt-2">
            <table class="table table-hover table-top">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Relation</th>
                        <th>DOB</th>
                        <th class="text-center">Active</th>
                    </tr>
                </thead>
        {% if beneficiary.dependent.all %}
                {% for dependent in beneficiary.dependent.all %}        
                
                <tr class="row-hover" data-href="{% url 'dependent-detail' dependent.pk %}">
                    <td>{{dependent.first_name}}</td>
                    <td>{{dependent.last_name}}</td>
                    <td>{{dependent.dependent_type}}</td>
                    <td>{{dependent.date_of_birth}}</td>
                    <td class="text-center">
                        {% if dependent.active %}
                            <i class="far fa-check-circle active-check "></i>
                        {% else %}
                            <i class="far fa-times-circle active-x "></i>
                        {% endif %}
                    </td>                    
                </tr>
                
                {% endfor %}
                
            </table>
        </div>
        {% endif %}
   

   </div>
</div> 

     
</div>
</div>

   
{% endblock %}




{% block navbar %}
    {% include "hr_leave_grant_app/navbar-links.html" %}
{% endblock %}

hr_leave_grant_app/templates/hr_leave_grant_app/beneficiary_list.html
{% extends "base_generic.html" %}



{% block content %}
<div class="card mt-5 card-border">
    <div class="card-body">

<div >
            <h4 class="">Leave Grant</h4>
            <h2 class="">Beneficiary List </h2>       
        </div>
   
<div class="row pb-4 mt-5 pt-2">
    <div class="col-sm-4 ">

        <form class="form-inline my-2 my-lg-0 " action="{% url 'beneficiary' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search Beneficiary" aria-label="Search" name='search' >
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-sm-12 ">
<table class="table table-hover table-top ">
    <thead class="table-header">
        <tr>
            <th scope="col">Beneficiary</th>            
            <th scope="col" class="text-center">Active</th>
        </tr>
    </thead>
    
    {% for  beneficiary in beneficiary_list %}
        <tr class="row-hover" data-href="{% url 'beneficiary-detail' beneficiary.pk %}">
            <td>
                {{beneficiary.first_name}} {{beneficiary.last_name}}              
            </td>
            
            <td class="text-center">
                {% if beneficiary.active %}
                    <i class="far fa-check-circle active-check "></i>
                {% else %}
                    <i class="far fa-times-circle active-x "></i>
                {% endif %}
            </td>
            
        </tr>
    {% endfor %}

</table>

<div class=" row mt-4 justify-content-center">
    <div>
        {% block pagination %}
            {% include "pagination.html" %}
        {% endblock %}
    </div>
</div>
</div>
</div>

{% endblock %}


{% block navbar %}
    {% include "hr_leave_grant_app/navbar-links.html" %}
{% endblock %}

hr_leave_grant_app/templates/hr_leave_grant_app/dependent_over18.html
{% extends "base_generic.html" %}



{% block content %}
<div class="card mt-5 card-border">
    <div class="card-body">

<div >
            <h4 class="">Leave Grant</h4>
            <h2 class="">Dependents Over 18 (Children)</h2>       
        </div>
   
<!-- <div class="row pb-4 mt-5 pt-2">
    <div class="col-sm-4 ">

        <form class="form-inline my-2 my-lg-0 " action="{% url 'beneficiary' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search Beneficiary" aria-label="Search" name='search' >
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</div> -->
<div class="row justify-content-center pb-4 mt-5 pt-2">
    <div class="col-sm-12 ">
<table class="table table-hover table-top ">
    <thead class="table-header">
        <tr>
            <th scope="col">Dependent</th>            
            <th scope="col" class="text-center">Active</th>
        </tr>
    </thead>
    
    {% for  dependent in dependent_list %}
        {% if dependent.over_18 %}
            <tr class="row-hover" data-href="{% url 'beneficiary-detail' dependent.beneficiary.pk %}">
                <td>
                    {{dependent.first_name}} {{dependent.last_name}}              
                </td>

                <td class="text-center">
                    {% if dependent.active %}
                        <i class="far fa-check-circle active-check "></i>
                    {% else %}
                        <i class="far fa-times-circle active-x "></i>
                    {% endif %}
                </td>

            </tr>
        {% endif %}    
      
    {% endfor %}

</table>
<div class=" row mt-4 justify-content-center">
    <div>
        {% block pagination %}
            {% include "pagination.html" %}
        {% endblock %}
    </div>
</div>
</div>
</div>








{% endblock %}


{% block navbar %}
    {% include "hr_leave_grant_app/navbar-links.html" %}
{% endblock %}

hr_leave_grant_app/templates/hr_leave_grant_app/pending_payment.html
{% extends "base_generic.html" %}



{% block content %}
<div class="card mt-5 card-border">
    <div class="card-body">

<div >
            <h4 class="">Leave Grant</h4>
            <h2 class="">Pending Payments </h2>       
        </div>
   
<!-- <div class="row pb-4 mt-5 pt-2">
    <div class="col-sm-4 ">

        <form class="form-inline my-2 my-lg-0 " action="{% url 'beneficiary' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search Beneficiary" aria-label="Search" name='search' >
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</div> -->

<div class="row justify-content-center pb-4 mt-5 pt-2">
    <div class="col-sm-12 ">
<table class="table table-hover table-top ">
    <thead class="table-header">
        <tr>
            <th scope="col">Beneficiary</th>            
            <th scope="col" class="text-center">Active</th>
        </tr>
    </thead>
    
    {% for  beneficiary in beneficiary_list %}
        <tr class="row-hover" data-href="{% url 'beneficiary-payment' beneficiary.pk %}">
            <td>
                {{beneficiary.first_name}} {{beneficiary.last_name}}              
            </td>
            
            <td class="text-center">
                {% if beneficiary.active %}
                    <i class="far fa-check-circle active-check "></i>
                {% else %}
                    <i class="far fa-times-circle active-x "></i>
                {% endif %}
            </td>
            
        </tr>
    {% endfor %}

</table>

<div class=" row mt-4 justify-content-center">
    <div>
        {% block pagination %}
            {% include "pagination.html" %}
        {% endblock %}
    </div>
</div>
</div>
</div>








{% endblock %}


{% block navbar %}
    {% include "hr_leave_grant_app/navbar-links.html" %}
{% endblock %}

hr_leave_grant_app/templates/hr_leave_grant_app/search_form.html
{% extends 'navbar-links.html' %}
{% block search_form %}
  <form class="form-inline my-2 my-lg-0 " action="{% url 'beneficiary' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search Beneficiary" aria-label="Search" name='search' >
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
  </form>
{% endblock %}

hr_leave_grant_app/templates/hr_leave_grant_app/transaction_history.html
{% extends "base_generic.html" %}



{% block content %}
<div class="card mt-5 card-border">
    <div class="card-body">

<div >
            <h4 class="">Leave Grant</h4>
            <h2 class="">Transaction History</h2>       
        </div>
   

<div class="row justify-content-center pb-4 mt-5 pt-2">
    <div class="col-sm-12 ">
<table class="table table-hover table-top ">
    <thead class="table-header">
        <tr>
            {% comment %} <th scope="col">Beneficiary</th> {% endcomment %}
            <th scope="col">Description</th> 
            {% comment %} <th scope="col">Leave Grant Year</th>  {% endcomment %}
            <th scope="col">Amount</th> 
            <th scope="col">Record Created</th> 
            <th scope="col">Payment Recorded</th>
            <th scope="col">Recorded By</th>           
            
        </tr>
    </thead>
    
    {% for  record in leave_grant_detail_list %}
        
        <tr class="row-hover" data-href="{% url 'beneficiary-payment' record.beneficiary.pk %}">
            {% comment %} <td>{{record.beneficiary.first_name}} {{record.beneficiary.last_name}}</td> {% endcomment %}
            <td>
               {{record.remarks}}             
            </td>
            {% comment %} <td>
                {% if record.transaction_year %}
                    {{record.transaction_year}}
                {% endif %}
            </td> {% endcomment %}
            <td>
                {{record.amount}}
            </td>
            <td>
                {{record.created_at}}
            </td>
            <td>
                {% if record.payment_date %}
                    {{record.payment_date}}
                {% endif %}
            </td>
            <td>
                {% if record.recorded_by %}
                    {{record.recorded_by}}
                {% endif %}
            </td>
        </tr>
      
      
    {% endfor %}

</table>
<div class=" row mt-4 justify-content-center">
    <div>
        {% block pagination %}
            {% include "pagination.html" %}
        {% endblock %}
    </div>
</div>
</div>
</div>








{% endblock %}


{% block navbar %}
    {% include "hr_leave_grant_app/navbar-links.html" %}
{% endblock %}